#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: c1050fe
#
# Source0 file verified with key 0x18EAA1890F7C882E (robert.ancell@gmail.com)
#
Name     : lightdm
Version  : 1.32.0
Release  : 18
URL      : https://github.com/canonical/lightdm/releases/download/1.32.0/lightdm-1.32.0.tar.xz
Source0  : https://github.com/canonical/lightdm/releases/download/1.32.0/lightdm-1.32.0.tar.xz
Source1  : lightdm.service
Source2  : lightdm.tmpfiles
Source3  : https://github.com/canonical/lightdm/releases/download/1.32.0/lightdm-1.32.0.tar.xz.asc
Summary  : LightDM client library
Group    : Development/Tools
License  : GPL-3.0 LGPL-2.0 LGPL-3.0
Requires: lightdm-bin = %{version}-%{release}
Requires: lightdm-config = %{version}-%{release}
Requires: lightdm-data = %{version}-%{release}
Requires: lightdm-lib = %{version}-%{release}
Requires: lightdm-libexec = %{version}-%{release}
Requires: lightdm-license = %{version}-%{release}
Requires: lightdm-locales = %{version}-%{release}
Requires: lightdm-man = %{version}-%{release}
Requires: lightdm-services = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : audit-dev
BuildRequires : buildreq-configure
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libxslt-bin
BuildRequires : perl(Getopt::Long)
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(libxklavier)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xdmcp)
BuildRequires : vala
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Disable-building-of-unused-yelp-documentation.patch
Patch2: 0002-Use-Clear-Linux-stateless-directories-by-default.patch
Patch3: 0003-common-Support-a-stateless-etc-lightdm-users.conf.patch
Patch4: 0004-Add-lightdm-session.patch
Patch5: 0005-Add-usr-share-defaults-etc-profile-to-be-sourced.patch

%description
LightDM is a cross-desktop display manager. A display manager is a daemon that:
- Runs display servers (e.g. X) where necessary.
- Runs greeters to allow users to pick which user account and session type to use.
- Allows greeters to perform authentication using PAM.
- Runs session processes once authentication is complete.
- Provides remote graphical login options.

%package bin
Summary: bin components for the lightdm package.
Group: Binaries
Requires: lightdm-data = %{version}-%{release}
Requires: lightdm-libexec = %{version}-%{release}
Requires: lightdm-config = %{version}-%{release}
Requires: lightdm-license = %{version}-%{release}
Requires: lightdm-services = %{version}-%{release}

%description bin
bin components for the lightdm package.


%package config
Summary: config components for the lightdm package.
Group: Default

%description config
config components for the lightdm package.


%package data
Summary: data components for the lightdm package.
Group: Data

%description data
data components for the lightdm package.


%package dev
Summary: dev components for the lightdm package.
Group: Development
Requires: lightdm-lib = %{version}-%{release}
Requires: lightdm-bin = %{version}-%{release}
Requires: lightdm-data = %{version}-%{release}
Provides: lightdm-devel = %{version}-%{release}
Requires: lightdm = %{version}-%{release}

%description dev
dev components for the lightdm package.


%package doc
Summary: doc components for the lightdm package.
Group: Documentation
Requires: lightdm-man = %{version}-%{release}

%description doc
doc components for the lightdm package.


%package extras
Summary: extras components for the lightdm package.
Group: Default

%description extras
extras components for the lightdm package.


%package lib
Summary: lib components for the lightdm package.
Group: Libraries
Requires: lightdm-data = %{version}-%{release}
Requires: lightdm-libexec = %{version}-%{release}
Requires: lightdm-license = %{version}-%{release}

%description lib
lib components for the lightdm package.


%package libexec
Summary: libexec components for the lightdm package.
Group: Default
Requires: lightdm-config = %{version}-%{release}
Requires: lightdm-license = %{version}-%{release}

%description libexec
libexec components for the lightdm package.


%package license
Summary: license components for the lightdm package.
Group: Default

%description license
license components for the lightdm package.


%package locales
Summary: locales components for the lightdm package.
Group: Default

%description locales
locales components for the lightdm package.


%package man
Summary: man components for the lightdm package.
Group: Default

%description man
man components for the lightdm package.


%package services
Summary: services components for the lightdm package.
Group: Systemd services
Requires: systemd

%description services
services components for the lightdm package.


%prep
%setup -q -n lightdm-1.32.0
cd %{_builddir}/lightdm-1.32.0
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
%patch -P 5 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702028563
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%reconfigure --disable-static --with-greeter-session=lightdm-gtk-greeter \
--enable-liblightdm-qt=no \
--enable-liblightdm-qt5=no \
--disable-tests
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1702028563
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lightdm
cp %{_builddir}/lightdm-%{version}/COPYING.GPL3 %{buildroot}/usr/share/package-licenses/lightdm/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/lightdm-%{version}/COPYING.LGPL2 %{buildroot}/usr/share/package-licenses/lightdm/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
cp %{_builddir}/lightdm-%{version}/COPYING.LGPL3 %{buildroot}/usr/share/package-licenses/lightdm/f45ee1c765646813b442ca58de72e20a64a7ddba || :
%make_install
%find_lang lightdm
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/lightdm.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/tmpfiles.d/lightdm.conf
## install_append content
install -D -d -m 00755 %{buildroot}/usr/lib/systemd/system/graphical.target.wants
ln -sv ../lightdm.service %{buildroot}/usr/lib/systemd/system/displaymanager.service
ln -sv ../lightdm.service %{buildroot}/usr/lib/systemd/system/graphical.target.wants/lightdm.service
install -D -m0755 lightdm-session %{buildroot}/usr/bin/lightdm-session
mv %{buildroot}/usr/share/dbus-1/system.d/org.freedesktop.DisplayManager.conf %{buildroot}/usr/share/dbus-1/system.d/lightdm_org.freedesktop.DisplayManager.conf
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dm-tool
/usr/bin/lightdm
/usr/bin/lightdm-session

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/lightdm.conf

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/LightDM-1.typelib
/usr/share/accountsservice/interfaces/org.freedesktop.DisplayManager.AccountsService.xml
/usr/share/bash-completion/completions/dm-tool
/usr/share/bash-completion/completions/lightdm
/usr/share/dbus-1/interfaces/org.freedesktop.DisplayManager.AccountsService.xml
/usr/share/dbus-1/system.d/lightdm_org.freedesktop.DisplayManager.conf
/usr/share/defaults/lightdm/keys.conf
/usr/share/defaults/lightdm/lightdm.conf
/usr/share/defaults/lightdm/users.conf
/usr/share/gir-1.0/*.gir
/usr/share/pam.d/lightdm
/usr/share/pam.d/lightdm-autologin
/usr/share/pam.d/lightdm-greeter
/usr/share/polkit-1/actions/org.freedesktop.DisplayManager.AccountsService.policy

%files dev
%defattr(-,root,root,-)
/usr/include/lightdm-gobject-1/lightdm.h
/usr/include/lightdm-gobject-1/lightdm/greeter.h
/usr/include/lightdm-gobject-1/lightdm/language.h
/usr/include/lightdm-gobject-1/lightdm/layout.h
/usr/include/lightdm-gobject-1/lightdm/power.h
/usr/include/lightdm-gobject-1/lightdm/session.h
/usr/include/lightdm-gobject-1/lightdm/system.h
/usr/include/lightdm-gobject-1/lightdm/user.h
/usr/lib64/liblightdm-gobject-1.so
/usr/lib64/pkgconfig/liblightdm-gobject-1.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/lightdm-gobject-1/LightDMGreeter.html
/usr/share/gtk-doc/html/lightdm-gobject-1/LightDMLanguage.html
/usr/share/gtk-doc/html/lightdm-gobject-1/LightDMLayout.html
/usr/share/gtk-doc/html/lightdm-gobject-1/LightDMSession.html
/usr/share/gtk-doc/html/lightdm-gobject-1/LightDMUser.html
/usr/share/gtk-doc/html/lightdm-gobject-1/LightDMUserList.html
/usr/share/gtk-doc/html/lightdm-gobject-1/annotation-glossary.html
/usr/share/gtk-doc/html/lightdm-gobject-1/api-index-full.html
/usr/share/gtk-doc/html/lightdm-gobject-1/ch01.html
/usr/share/gtk-doc/html/lightdm-gobject-1/home.png
/usr/share/gtk-doc/html/lightdm-gobject-1/index.html
/usr/share/gtk-doc/html/lightdm-gobject-1/left-insensitive.png
/usr/share/gtk-doc/html/lightdm-gobject-1/left.png
/usr/share/gtk-doc/html/lightdm-gobject-1/lightdm-gobject-1-Power-Management.html
/usr/share/gtk-doc/html/lightdm-gobject-1/lightdm-gobject-1-System-Information.html
/usr/share/gtk-doc/html/lightdm-gobject-1/lightdm-gobject-1.devhelp2
/usr/share/gtk-doc/html/lightdm-gobject-1/object-tree.html
/usr/share/gtk-doc/html/lightdm-gobject-1/right-insensitive.png
/usr/share/gtk-doc/html/lightdm-gobject-1/right.png
/usr/share/gtk-doc/html/lightdm-gobject-1/style.css
/usr/share/gtk-doc/html/lightdm-gobject-1/up-insensitive.png
/usr/share/gtk-doc/html/lightdm-gobject-1/up.png

%files extras
%defattr(-,root,root,-)
/usr/lib/systemd/system/displaymanager.service
/usr/lib/systemd/system/graphical.target.wants/lightdm.service

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblightdm-gobject-1.so.0
/usr/lib64/liblightdm-gobject-1.so.0.0.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/lightdm-guest-session

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lightdm/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/lightdm/ba8966e2473a9969bdcab3dc82274c817cfd98a1
/usr/share/package-licenses/lightdm/f45ee1c765646813b442ca58de72e20a64a7ddba

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/dm-tool.1
/usr/share/man/man1/lightdm.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/lightdm.service

%files locales -f lightdm.lang
%defattr(-,root,root,-)

