#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lightdm
Version  : 1.18.3
Release  : 5
URL      : https://launchpad.net/lightdm/1.18/1.18.3/+download/lightdm-1.18.3.tar.xz
Source0  : https://launchpad.net/lightdm/1.18/1.18.3/+download/lightdm-1.18.3.tar.xz
Source1  : lightdm.service
Source2  : lightdm.tmpfiles
Summary  : LightDM client library
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-3.0
Requires: lightdm-bin
Requires: lightdm-config
Requires: lightdm-lib
Requires: lightdm-data
Requires: lightdm-doc
Requires: lightdm-locales
BuildRequires : Linux-PAM-dev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gettext-bin
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : itstool
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libxslt-bin
BuildRequires : m4
BuildRequires : perl(XML::Parser)
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(libxklavier)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcb)
Patch1: 0001-Use-Clear-Linux-stateless-directories-by-default.patch
Patch2: 0002-Explicitly-provide-a-session-wrapper-script.patch
Patch3: 0003-Disable-building-of-unused-yelp-documentation.patch

%description
No detailed description available

%package bin
Summary: bin components for the lightdm package.
Group: Binaries
Requires: lightdm-data
Requires: lightdm-config

%description bin
bin components for the lightdm package.


%package config
Summary: config components for the lightdm package.
Group: Default

%description config
config components for the lightdm package.


%package data
Summary: data components for the lightdm package.
Group: Data

%description data
data components for the lightdm package.


%package dev
Summary: dev components for the lightdm package.
Group: Development
Requires: lightdm-lib
Requires: lightdm-bin
Requires: lightdm-data
Provides: lightdm-devel

%description dev
dev components for the lightdm package.


%package doc
Summary: doc components for the lightdm package.
Group: Documentation

%description doc
doc components for the lightdm package.


%package lib
Summary: lib components for the lightdm package.
Group: Libraries
Requires: lightdm-data
Requires: lightdm-config

%description lib
lib components for the lightdm package.


%package locales
Summary: locales components for the lightdm package.
Group: Default

%description locales
locales components for the lightdm package.


%prep
%setup -q -n lightdm-1.18.3
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export LANG=C
%reconfigure --disable-static --with-greeter-session=lightdm-gtk-greeter
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install
%find_lang lightdm
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/lightdm.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/tmpfiles.d/lightdm.conf
## make_install_append content
install -D -d -m 00755 %{buildroot}/usr/lib/systemd/system/graphical.target.wants
ln -sv ../lightdm.service %{buildroot}/usr/lib/systemd/system/displaymanager.service
ln -sv ../lightdm.service %{buildroot}/usr/lib/systemd/system/graphical.target.wants/lightdm.service
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dm-tool
/usr/bin/lightdm
/usr/bin/lightdm-wrapper
/usr/libexec/lightdm-guest-session

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/displaymanager.service
/usr/lib/systemd/system/graphical.target.wants/lightdm.service
/usr/lib/systemd/system/lightdm.service
/usr/lib/tmpfiles.d/lightdm.conf

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/dm-tool
/usr/share/bash-completion/completions/lightdm
/usr/share/dbus-1/system.d/org.freedesktop.DisplayManager.conf
/usr/share/gir-1.0/LightDM-1.gir
/usr/share/pam.d/lightdm
/usr/share/pam.d/lightdm-autologin
/usr/share/pam.d/lightdm-greeter

%files dev
%defattr(-,root,root,-)
/usr/include/lightdm-gobject-1/lightdm.h
/usr/include/lightdm-gobject-1/lightdm/greeter.h
/usr/include/lightdm-gobject-1/lightdm/language.h
/usr/include/lightdm-gobject-1/lightdm/layout.h
/usr/include/lightdm-gobject-1/lightdm/power.h
/usr/include/lightdm-gobject-1/lightdm/session.h
/usr/include/lightdm-gobject-1/lightdm/system.h
/usr/include/lightdm-gobject-1/lightdm/user.h
/usr/lib64/*.so
/usr/lib64/girepository-1.0/LightDM-1.typelib
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
/usr/share/gtk-doc/html/lightdm-gobject-1/core.html
/usr/share/gtk-doc/html/lightdm-gobject-1/home.png
/usr/share/gtk-doc/html/lightdm-gobject-1/index.html
/usr/share/gtk-doc/html/lightdm-gobject-1/left-insensitive.png
/usr/share/gtk-doc/html/lightdm-gobject-1/left.png
/usr/share/gtk-doc/html/lightdm-gobject-1/lightdm-gobject-1-Greeter-Interface.html
/usr/share/gtk-doc/html/lightdm-gobject-1/lightdm-gobject-1-Keyboard-Layout.html
/usr/share/gtk-doc/html/lightdm-gobject-1/lightdm-gobject-1-Languages.html
/usr/share/gtk-doc/html/lightdm-gobject-1/lightdm-gobject-1-Power-Management.html
/usr/share/gtk-doc/html/lightdm-gobject-1/lightdm-gobject-1-Sessions.html
/usr/share/gtk-doc/html/lightdm-gobject-1/lightdm-gobject-1-System-Information.html
/usr/share/gtk-doc/html/lightdm-gobject-1/lightdm-gobject-1-User-Accounts.html
/usr/share/gtk-doc/html/lightdm-gobject-1/lightdm-gobject-1.devhelp2
/usr/share/gtk-doc/html/lightdm-gobject-1/right-insensitive.png
/usr/share/gtk-doc/html/lightdm-gobject-1/right.png
/usr/share/gtk-doc/html/lightdm-gobject-1/style.css
/usr/share/gtk-doc/html/lightdm-gobject-1/up-insensitive.png
/usr/share/gtk-doc/html/lightdm-gobject-1/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files locales -f lightdm.lang 
%defattr(-,root,root,-)

