#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lightdm
Version  : 1.26.0
Release  : 12
URL      : https://github.com/CanonicalLtd/lightdm/archive/1.26.0.tar.gz
Source0  : https://github.com/CanonicalLtd/lightdm/archive/1.26.0.tar.gz
Source1  : lightdm.service
Source2  : lightdm.tmpfiles
Summary  : LightDM Qt5 client library
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-3.0
Requires: lightdm-bin
Requires: lightdm-config
Requires: lightdm-autostart
Requires: lightdm-data
Requires: lightdm-lib
Requires: lightdm-license
Requires: lightdm-locales
Requires: lightdm-man
BuildRequires : Linux-PAM-dev
BuildRequires : audit-dev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gettext-bin
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : itstool
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libxslt-bin
BuildRequires : m4
BuildRequires : perl(XML::Parser)
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(libxklavier)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xdmcp)
BuildRequires : vala
Patch1: 0001-Disable-building-of-unused-yelp-documentation.patch
Patch2: 0002-Use-Clear-Linux-stateless-directories-by-default.patch
Patch3: 0003-common-Support-a-stateless-configuration-for-etc-lig.patch

%description
[![Build Status](https://travis-ci.org/CanonicalLtd/lightdm.svg?branch=master)](https://travis-ci.org/CanonicalLtd/lightdm)

%package autostart
Summary: autostart components for the lightdm package.
Group: Default

%description autostart
autostart components for the lightdm package.


%package bin
Summary: bin components for the lightdm package.
Group: Binaries
Requires: lightdm-data
Requires: lightdm-config
Requires: lightdm-license
Requires: lightdm-man

%description bin
bin components for the lightdm package.


%package config
Summary: config components for the lightdm package.
Group: Default

%description config
config components for the lightdm package.


%package data
Summary: data components for the lightdm package.
Group: Data

%description data
data components for the lightdm package.


%package dev
Summary: dev components for the lightdm package.
Group: Development
Requires: lightdm-lib
Requires: lightdm-bin
Requires: lightdm-data
Provides: lightdm-devel

%description dev
dev components for the lightdm package.


%package doc
Summary: doc components for the lightdm package.
Group: Documentation
Requires: lightdm-man

%description doc
doc components for the lightdm package.


%package extras
Summary: extras components for the lightdm package.
Group: Default

%description extras
extras components for the lightdm package.


%package lib
Summary: lib components for the lightdm package.
Group: Libraries
Requires: lightdm-data
Requires: lightdm-license

%description lib
lib components for the lightdm package.


%package license
Summary: license components for the lightdm package.
Group: Default

%description license
license components for the lightdm package.


%package locales
Summary: locales components for the lightdm package.
Group: Default

%description locales
locales components for the lightdm package.


%package man
Summary: man components for the lightdm package.
Group: Default

%description man
man components for the lightdm package.


%prep
%setup -q -n lightdm-1.26.0
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532084091
%autogen --disable-static --with-greeter-session=lightdm-gtk-greeter \
--enable-liblightdm-qt=no \
--enable-liblightdm-qt5=no \
--disable-tests
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1532084091
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/lightdm
cp COPYING.LGPL3 %{buildroot}/usr/share/doc/lightdm/COPYING.LGPL3
cp COPYING.LGPL2 %{buildroot}/usr/share/doc/lightdm/COPYING.LGPL2
cp COPYING.GPL3 %{buildroot}/usr/share/doc/lightdm/COPYING.GPL3
cp debian/copyright %{buildroot}/usr/share/doc/lightdm/debian_copyright
%make_install
%find_lang lightdm
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/lightdm.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/tmpfiles.d/lightdm.conf
## make_install_append content
install -D -d -m 00755 %{buildroot}/usr/lib/systemd/system/graphical.target.wants
ln -sv ../lightdm.service %{buildroot}/usr/lib/systemd/system/displaymanager.service
ln -sv ../lightdm.service %{buildroot}/usr/lib/systemd/system/graphical.target.wants/lightdm.service
## make_install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/graphical.target.wants/lightdm.service

%files bin
%defattr(-,root,root,-)
/usr/bin/dm-tool
/usr/bin/lightdm
/usr/libexec/lightdm-guest-session

%files config
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/displaymanager.service
%exclude /usr/lib/systemd/system/graphical.target.wants/lightdm.service
/usr/lib/systemd/system/lightdm.service
/usr/lib/tmpfiles.d/lightdm.conf

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/LightDM-1.typelib
/usr/share/accountsservice/interfaces/org.freedesktop.DisplayManager.AccountsService.xml
/usr/share/bash-completion/completions/dm-tool
/usr/share/bash-completion/completions/lightdm
/usr/share/dbus-1/interfaces/org.freedesktop.DisplayManager.AccountsService.xml
/usr/share/dbus-1/system.d/org.freedesktop.DisplayManager.conf
/usr/share/defaults/lightdm/keys.conf
/usr/share/defaults/lightdm/lightdm.conf
/usr/share/defaults/lightdm/users.conf
/usr/share/gir-1.0/*.gir
/usr/share/pam.d/lightdm
/usr/share/pam.d/lightdm-autologin
/usr/share/pam.d/lightdm-greeter
/usr/share/polkit-1/actions/org.freedesktop.DisplayManager.AccountsService.policy

%files dev
%defattr(-,root,root,-)
/usr/include/lightdm-gobject-1/lightdm.h
/usr/include/lightdm-gobject-1/lightdm/greeter.h
/usr/include/lightdm-gobject-1/lightdm/language.h
/usr/include/lightdm-gobject-1/lightdm/layout.h
/usr/include/lightdm-gobject-1/lightdm/power.h
/usr/include/lightdm-gobject-1/lightdm/session.h
/usr/include/lightdm-gobject-1/lightdm/system.h
/usr/include/lightdm-gobject-1/lightdm/user.h
/usr/lib64/liblightdm-gobject-1.so
/usr/lib64/pkgconfig/liblightdm-gobject-1.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/lightdm/*

%files extras
%defattr(-,root,root,-)
/usr/lib/systemd/system/displaymanager.service
/usr/lib/systemd/system/graphical.target.wants/lightdm.service

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblightdm-gobject-1.so.0
/usr/lib64/liblightdm-gobject-1.so.0.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/lightdm/COPYING.GPL3
/usr/share/doc/lightdm/COPYING.LGPL2
/usr/share/doc/lightdm/COPYING.LGPL3

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/dm-tool.1
/usr/share/man/man1/lightdm.1

%files locales -f lightdm.lang
%defattr(-,root,root,-)

